name: 'build-and-publish-api'
description: 'Builds API project and publish its image'

inputs:
  releaseVersion:
    required: true
    description: "Release Version (Commit or Tag)"
  containerRegistryUrl:
    required: true
    description: "Container registry url"
  containerRegistryUsername:
    required: true
    description: "Container registry username"
  containerRegistryPassword:
    required: true
    description: "Container registry password"
  containerTags:
    required: true
    description: "Container tag or csv delimited tags"

runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.containerRegistryUrl }}
        username: ${{ inputs.containerRegistryUsername }}
        password: ${{ inputs.containerRegistryPassword }}
    - name: Create Environment
      run: envsubst < apps/api/src/app/environment.template > apps/api/src/app/environment.ts
      shell: bash
      env:
        RELEASE_VERSION: ${{ inputs.releaseVersion }}
    - name: Build app
      run: |
        npx nx build api --prod
      shell: bash
    - id: node-version-check
      run: echo "node-version=$(cat .nvmrc | tr -cd '[:digit:].')" >> $GITHUB_OUTPUT
      shell: bash
    - name: Build and push image
      uses: docker/build-push-action@v6
      with:
        context: ./
        file: ./apps/api/Dockerfile
        build-args: |
          NODE_VERSION=${{ steps.node-version-check.outputs.node-version }}
        push: true
        tags: ${{ inputs.containerTags }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
