name: 'build-and-publish-api'
description: 'Builds API project and publish its image'

inputs:
  releaseVersion:
    required: true
    description: "Release Version (Commit or Tag)"
  containerRegistryUrl:
    required: true
    description: "Container registry url"
  containerRegistryUsername:
    required: true
    description: "Container registry username"
  containerRegistryPassword:
    required: true
    description: "Container registry password"
  containerTags:
    required: true
    description: "Container tag or csv delimited tags"

runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.containerRegistryUrl }}
        username: ${{ inputs.containerRegistryUsername }}
        password: ${{ inputs.containerRegistryPassword }}
    - name: Create Environment
      run: envsubst < apps/api/src/app/environment.template > apps/api/src/app/environment.ts
      shell: bash
      env:
        RELEASE_VERSION: ${{ inputs.releaseVersion }}
    - name: Build app
      run: |
        npx nx build api --prod
      shell: bash
    - id: node-version-check
      run: echo "node-version=$(cat .nvmrc | tr -cd '[:digit:].')" >> $GITHUB_OUTPUT
      shell: bash
    - name: Build and push image
      uses: docker/build-push-action@v5
      with:
        context: ./
        file: ./apps/api/Dockerfile
        build-args: |
          NODE_VERSION=${{ steps.node-version-check.outputs.node-version }}
        push: true
        tags: ${{ inputs.containerTags }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
    - name: Set environment for deployment
      run: envsubst < apps/api/src/.env.template > dist/apps/api/.env
      env:
        MONGODB_URI: ${{ inputs.mongoUri }}
        ENVIRONMENT_NAME: ${{ inputs.slot }}
        RELEASE_VERSION: ${{ inputs.releaseVersion }}
        SENTRY_KEY: ${{ inputs.sentryKey }}
      shell: bash
    - name: Deploy API
      id: wa-deployment
      run: echo "url=placeholder" >> $GITHUB_OUTPUT
      shell: bash
    - name: Create Sentry release
      uses: getsentry/action-release@v1
      env:
        SENTRY_AUTH_TOKEN: ${{ inputs.sentryAuthToken }}
        SENTRY_ORG: kordis-leitstelle
        SENTRY_PROJECT: kordis-api
      with:
        environment: ${{ inputs.slot }}
        version: ${{ inputs.releaseVersion }}
        sourcemaps: ./dist/apps/api
