name: 'build-and-deploy-spa'
description: 'Builds SPA project for production and deploys it to a given environment'

inputs:
  releaseVersion:
    required: true
    description: "Release Version (Commit or Tag)"
  deploymentEnv:
    required: true
    description: "Deployment Environment"
  sentryAuthToken:
    required: true
    description: "Sentry Auth Token"
  containerRegistryUrl:
    required: true
    description: "Container registry url"
  containerRegistryUsername:
    required: true
    description: "Container registry username"
  containerRegistryPassword:
    required: true
    description: "Container registry password"
outputs:
  url:
    description: "SPA URL"
    value: ${{ steps.spa-deployment.outputs.static_web_app_url  }}

runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.containerRegistryUrl }}
        username: ${{ inputs.containerRegistryUsername }}
        password: ${{ inputs.containerRegistryPassword }}
    - run: envsubst < apps/spa/src/environments/environment.template > apps/spa/src/environments/environment.ts
      shell: bash
      env:
        IS_PRODUCTION: true
        ENVIRONMENT_NAME: ${{ inputs.deploymentEnv }}
        RELEASE_VERSION: ${{ inputs.releaseVersion }}
    - run: |
        npx nx build spa --prod
        npx --yes generate-license-file@3.0.1 --input package.json --output dist/apps/spa/browser/assets/third-party-licenses.txt --ci
      shell: bash
    - name: Build and push image
      uses: docker/build-push-action@v5
      with:
        context: ./
        file: ./apps/spa/docker/Dockerfile
        push: true
        tags: |
          ghcr.io/kordis-leitstelle/kordis-spa:${{inputs.releaseVersion}}
        cache-from: type=gha
        cache-to: type=gha,mode=max
    - name: Deploy SPA
      id: spa-deployment
      shell: bash
      run: echo "url=placeholder" >> $GITHUB_OUTPUT
    - name: Build SPA with source maps for sentry
      run: npx nx build spa --prod --source-map=true
      shell: bash
    - name: Create Sentry release
      uses: getsentry/action-release@v1
      env:
        SENTRY_AUTH_TOKEN: ${{ inputs.sentryAuthToken }}
        SENTRY_ORG: kordis-leitstelle
        SENTRY_PROJECT: kordis-spa
      with:
        environment: ${{ inputs.deploymentEnv }}
        version: ${{ inputs.releaseVersion }}
        sourcemaps: ./dist/apps/spa
