name: 'build-and-deploy-spa'
description: 'Builds SPA Project for Production and Deploys it to a given SWA Environment'

inputs:
  apiUrl:
    required: true
    description: "Base URL of the API"
  oauthConfig:
    required: true
    description: "OAuthConfig from the angular-oauth2-oidc package"
  releaseVersion:
    required: true
    description: "Release Version (Commit or Tag)"
  deploymentEnv:
    required: true
    description: "Azure SWA Deployment Environment"
  publishToken:
    required: true
    description: "Azure Static Web App Deployment Token"
  sentryKey:
    required: false
    description: "Sentry DSN Key"
outputs:
  url:
    description: "SPA URL"
    value: ${{ steps.spa-deployment.outputs.static_web_app_url  }}

runs:
  using: "composite"
  steps:
    - run: |
        envsubst < apps/spa/src/environments/environment.template > apps/spa/src/environments/environment.prod.ts
        npx nx build spa --prod
      shell: bash
      env:
        IS_PRODUCTION: true
        ENVIRONMENT_NAME: ${{ inputs.deploymentEnv }}
        API_URL: ${{ inputs.apiUrl }}
        OAUTH_CONFIG: ${{ inputs.oauthConfig }}
        RELEASE_VERSION: ${{ inputs.releaseVersion }}
        SENTRY_KEY: ${{ inputs.sentryKey }}
    - name: Deploy SPA
      id: spa-deployment
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ inputs.publishToken }}
        action: "upload"
        app_location: "dist/apps/spa/"
        output_location: ''
        skip_app_build: true
        skip_api_build: true
        deployment_environment: ${{ inputs.deploymentEnv }}
