name: 'build-and-deploy-spa'
description: 'Builds SPA Project for Production and Deploys it to a given SWA Environment'

inputs:
  apiUrl:
    required: true
    description: "Base URL of the API"
  deploymentName:
    required: true
    description: "Unique identifier for the Deployment"
  deploymentEnv:
    required: true
    description: "Azure SWA Deployment Environment"
  angularEnvironment:
    required: true
    description: "Angular Environment to use from the project.json"
  publishToken:
    required: true
    description: "Azure Static Web App Deployment Token"
outputs:
  url:
    description: "SPA URL"
    value: ${{ steps.spa-deployment.outputs.static_web_app_url  }}

runs:
  using: "composite"
  steps:
    - run: |
        envsubst < apps/spa/src/environments/environment.template > apps/spa/src/environments/environment.${{ inputs.angularEnvironment }}.ts
        npx nx build spa --prod --configuration=${{ inputs.angularEnvironment }}
      shell: bash
      env:
        IS_PRODUCTION: true
        DEPLOYMENT_NAME: ${{ inputs.deploymentName }}
        API_URL: ${{ inputs.apiUrl }}
    - name: Deploy SPA
      id: spa-deployment
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ inputs.publishToken }}
        action: "upload"
        app_location: "dist/apps/spa/"
        output_location: ''
        skip_app_build: true
        skip_api_build: true
        deployment_environment: ${{ inputs.deploymentEnv }}
