name: 'build-and-deploy-api'
description: 'Builds API Project for Production and Deploys it to a given WA Slot'

inputs:
  releaseVersion:
    required: true
    description: "Release Version (Commit or Tag)"
  slot:
    required: true
    description: "Slot Identifier"
  mongoUri:
    required: true
    description: "Mongo Connection URI"
  sentryKey:
    required: false
    description: "Sentry DSN Key"
outputs:
  url:
    description: "API URL"
    value: ${{ steps.wa-deployment.outputs.webapp-url }}

runs:
  using: "composite"
  steps:
    - run: envsubst < apps/api/src/.env.template > apps/api/src/.env
      env:
        MONGODB_URI: ${{ inputs.mongoUri }}
        ENVIRONMENT_NAME: ${{ inputs.slot }}
        RELEASE_VERSION: ${{ inputs.releaseVersion }}
        SENTRY_KEY: ${{ inputs.sentryKey }}
      shell: bash
    - run: |
        npx nx build api --prod
        cd dist/apps/api
        npm i --omit=dev --ignore-scripts
      shell: bash
    - name: Deploy API
      id: wa-deployment
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'kordis-api'
        slot-name: ${{ inputs.slot }}
        package: dist/apps/api/
