on:
  push:
    branches:
      - main

jobs:
  set-is-affected:
    uses: ./.github/workflows/check-affected.yml
    with:
      APP_NAME: api
  build-and-deploy:
    if: env.IS_AFFECTED == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - run: npm ci
      - name: Build API
        run: npx nx build api
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'kordis-api'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_API_PUBLISH_PROFILE }}
