name: PR Title Check
on:
  pull_request:
    types:
      - opened
      - edited

jobs:
  check-pr-title:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
